export default function Terms() {
  return (
    <main className="legal">
      <p className="eyebrow">
        LEGAL
      </p>

      <h1>
        Terms of Service & Privacy Notice
      </h1>

      <p>
        <b>
          Last updated: August 2026
        </b>
      </p>

      <h2>
        1. Acceptance of Terms
      </h2>

      <p>
        By accessing or using FootyPredictor,
        you agree to these Terms of Service.
        If you do not agree with these terms,
        you should stop using the service.
      </p>

      <h2>
        2. Description of the Service
      </h2>

      <p>
        FootyPredictor provides football
        information, fixtures, predictions,
        competitions, private leagues,
        leaderboards and related features.
        Information and predictions are
        provided for entertainment and
        informational purposes.
      </p>

      <h2>
        3. Predictions
      </h2>

      <p>
        Predictions generated by FootyPredictor
        are estimates and are not guarantees.
        Football results, goalscorers, cards,
        statistics and other events may differ
        from predictions.
      </p>

      <h2>
        4. Third-Party Football Data
      </h2>

      <p>
        FootyPredictor may obtain football
        information from third-party providers.
        Third-party information may be delayed,
        corrected, incomplete or unavailable.
      </p>

      <h2>
        5. User Accounts
      </h2>

      <p>
        Users are responsible for maintaining
        the security of their account and
        should not share their authentication
        credentials with other people.
      </p>

      <h2>
        6. Google Authentication
      </h2>

      <p>
        Where Google authentication is offered,
        the application requests only the
        permissions required for the
        authentication functionality that has
        been configured. Information made
        available through authentication may be
        processed for account creation,
        authentication, security and operation
        of the service.
      </p>

      <h2>
        7. Information We Process
      </h2>

      <p>
        Depending on the features you use,
        FootyPredictor may process information
        such as your account identifier,
        email address, display name,
        predictions, private league membership,
        favorite teams, technical information
        and information necessary to operate
        and secure the service.
      </p>

      <h2>
        8. Information You Provide
      </h2>

      <p>
        You should only provide information
        that you are authorized to provide.
        Do not submit passwords, API keys,
        financial credentials or confidential
        information through prediction,
        profile or league fields.
      </p>

      <h2>
        9. Advertising
      </h2>

      <p>
        FootyPredictor may display advertising
        and sponsored links provided by
        third-party advertising networks.
        Advertising providers may use cookies,
        identifiers, scripts or similar
        technologies subject to their own
        policies and applicable law.
      </p>

      <h2>
        10. Advertising Interaction
      </h2>

      <p>
        Users must not artificially generate
        impressions, clicks or other advertising
        activity. Attempts to manipulate
        advertising systems may result in
        account restrictions or termination.
      </p>

      <h2>
        11. Private Leagues
      </h2>

      <p>
        Private leagues allow users to create
        competitions and invite other users.
        League owners are responsible for
        sharing invitation codes appropriately.
      </p>

      <h2>
        12. User Content
      </h2>

      <p>
        Information submitted by users may be
        processed as necessary to provide the
        requested functionality, operate
        private leagues, calculate predictions
        and maintain service security.
      </p>

      <h2>
        13. Prohibited Activities
      </h2>

      <p>
        Users may not attempt unauthorized
        access, attack the service, circumvent
        security controls, manipulate
        leaderboards, abuse APIs, distribute
        malware, impersonate another person,
        infringe intellectual property rights,
        or use the service for unlawful
        purposes.
      </p>

      <h2>
        14. Availability
      </h2>

      <p>
        FootyPredictor may experience
        maintenance, outages, API limitations,
        provider failures, technical errors or
        interruptions. Continuous availability
        is not guaranteed.
      </p>

      <h2>
        15. Accuracy
      </h2>

      <p>
        Football information is supplied on an
        informational basis. We do not guarantee
        that fixtures, results, standings,
        player information, cards, goals,
        predictions or other statistics are
        always accurate or current.
      </p>

      <h2>
        16. Intellectual Property
      </h2>

      <p>
        FootyPredictor's original software,
        branding, interface and original
        content belong to their respective
        owners to the extent permitted by law.
        Third-party names, trademarks and data
        remain the property of their respective
        owners.
      </p>

      <h2>
        17. Third-Party Services
      </h2>

      <p>
        FootyPredictor may use third-party
        infrastructure and services including
        authentication, hosting, football-data
        providers and advertising networks.
        Those providers may have separate
        terms and privacy policies.
      </p>

      <h2>
        18. Security
      </h2>

      <p>
        Reasonable technical safeguards are
        used to protect the service. However,
        no internet-connected service can
        guarantee absolute security.
      </p>

      <h2>
        19. Data Retention
      </h2>

      <p>
        Information may be retained for as long
        as reasonably necessary to operate the
        service, maintain security, resolve
        disputes, enforce terms and satisfy
        legal obligations.
      </p>

      <h2>
        20. Account Termination
      </h2>

      <p>
        Accounts or content may be suspended
        or terminated where reasonably necessary
        to protect the service, comply with law,
        investigate abuse or enforce these
        Terms.
      </p>

      <h2>
        21. Limitation of Liability
      </h2>

      <p>
        To the maximum extent permitted by
        applicable law, FootyPredictor and its
        operators will not be responsible for
        indirect, incidental, consequential,
        special or punitive losses arising from
        use of the service.
      </p>

      <h2>
        22. Disclaimer
      </h2>

      <p>
        The service is provided on an
        informational and entertainment basis.
        Nothing in the service constitutes
        financial, legal, professional or
        investment advice.
      </p>

      <h2>
        23. Changes to These Terms
      </h2>

      <p>
        These Terms may be updated from time to
        time. Continued use after an update may
        constitute acceptance where permitted
        by applicable law.
      </p>

      <h2>
        24. Privacy Requests
      </h2>

      <p>
        Users may contact the service operator
        through the contact method made
        available by FootyPredictor regarding
        privacy or account-related questions.
      </p>

      <h2>
        25. Legal Review
      </h2>

      <p>
        This document is a general software
        terms template and is not a substitute
        for advice from a qualified lawyer.
        Because privacy, consumer, advertising
        and data-protection laws differ between
        jurisdictions, the operator should have
        these terms and the application's actual
        data practices reviewed before launch.
      </p>
    </main>
  );
}
